###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${Pega_SignIn_URL}    https://customerservice-dev.aflac.com/prweb

#==========================================================================#
#                             Users                                        #
#==========================================================================#
# For C360 and SmartScreens Users please see Agent and PolicyHolder Dev.resource files