###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables

${SS_Pega_SignIn_URL}        https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService

#==========================================================================#
#                             Users                                        #
#==========================================================================#
# For C360 and SmartScreens Users please see Agent and PolicyHolder SysT.resource files