###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}              http://customerservicechat-dev.aflac.com/AflacChatbotAgent/index.html
${Pega_SignIn_URL}          https://customerservice-dev.aflac.com/prweb


# Everwell CCS Logins
${Everwell_ccs_uName}       ESCSR1
${gPWD}                     Ani_P@v3R$01

# Everwell Username
${gLoggedInUserName}        Darvin

