###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}        https://www.intg.everwellbenefits.com/producer/login    #http://customerservicechat-intg.aflac.com/AflacChatbotAgent/index1.html
${Pega_SignIn_URL}    https://customerservice-intg.aflac.com/prweb


# Everwell CCS Logins
${Everwell_ccs_uName}    ESCSR1
${gPWD}                  Ani_P@v3R$01

# Everwell Username
${gLoggedInUserName}    Darvin

#Digital Market Everwell ccs logins
${DM_Everwell_ccs_uName}    mk@aflac
${DM_Everwell_ccs_password}    test