###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}            https://www.syst.everwellbenefits.com/producer/login
${Pega_SignIn_URL}        https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService
${sso_Pega_SignIn_URL}    https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService

#Digital Market Everwell ccs logins
${DM_Everwell_ccs_uName}    auto20@aflac
${DM_Everwell_ccs_password}    test

# SSO Everwell CCS Logins
${sso_Everwell}                   EF0218
${sso_Everwell_pwd}               wS$@gO0U

# Everwell CCS Logins
${Everwell_ccS_uName}    EverwellSpecialist_ccr
${gPWD}                  rules

# SSO Agent Logins
${sso_agent}        darci_wertz
${sso_agent_pwd}    Ani_P@v3R$6
${gLoggedInUserName}    Darci

# SSO CCS Logins
${sso_ccsUser}        EF0705
${sso_ccsUser_pwd}    T6x4xv7VxBiP5ch

${sso_ccsManager}        EF0706
${sso_ccsManager_pwd}    A4xxGv2x7EaK8qr

${sso_ccsAdmin}         EF0707
${sso_ccsAdmin_pwd}     o64xlxQ5Ix7XBcL
# ${gLoggedInUserName}    Geno

${sso_ccsDeveloper}        EF0708
${sso_ccsDeveloper_pwd}    ErxSl6x85x7zgP4

