###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}                          http://customerservicechat-dev.aflac.com/AflacWebChatbot/index.html
${Pega_SignIn_URL}                      https://customerservice-dev.aflac.com/prweb

#==========================================================================#
#                          C360 Users			                           #
#==========================================================================#
# PolicyHolder CCS Logins
${PolicyHolder_ccs_uName}               PHS001
${PolicyHolderAccount_ccs_uName}        PHS002
${PolicyHolderSearch_ccs_uName}         PHS003
${PHClaims_ccs_uName}                   PHS004
${PHPayment_ccs_uName}                  PHS005
${PolicyHolderClaims_ccs_uName}         PHS006
${PolicyHolderPayment_ccs_uName}        PHS007
${PolicyHolderEF_ccs_uName}             EF0202
${PolicyHolderBeeline_ccs_uName}        PHS008
${PHPaymentSupervisor_ccs_uName}        PHS009

# AgentChannel PolicyHolder CCS Logins
${AgentSearch_ccs_uName}                AS0001

# AccountChannel PolicyHolder CCS Logins
${PHAccount_ccs_uName}                  PHA001

# PolicyHolder, AccountChannel and AgentChannel C360 Pwd
${gPWD}                                 Aflac@001

#==========================================================================#
#                      SmartScreens Users	           		               #
#==========================================================================#
# PolicyHolder SmartScreen Logins
${SSUser_ccs_uName}                     SSU000
${SSOneUser_ccs_uName}                  SSU001
${SSTwoUser_ccs_uName}                  SSU002
${SSThreeUser_ccs_uName}                SSU003
${SSFourUser_ccs_uName}                 SSU004
${SSFiveUser_ccs_uName}                 SSU005
${SSSixUser_ccs_uName}                  SSU006

# AgentChannel SmartScreen Logins
${SSAgentUser_ccs_uName}                SSUA01

# AccountChannel SmartScreen Logins
${SSAccountUser_ccs_uName}              SSAU00
${SSAccountOneUser_ccs_uName}           SSAU01
${SSAccountTwoUser_ccs_uName}           SSAU02

# PolicyHolder, AccountChannel and AgentChannel SmartScreen Pwd
${SSUser_ccs_uPwd}                      Aflac@002

