###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}                      https://${DM_PH_ccs_uName}:${DM_PH_ccs_password}@gamma.aflac.com/contact-aflac/default.aspx
${Pega_SignIn_URL}                  https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService
${sso_Pega_SignIn_URL}              https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService

#==========================================================================#
#                          C360 Users			                           #
#==========================================================================#
# SSO PolicyHolder CCS Logins
${sso_PolicyHolder}                 EF0203
${sso_PolicyHolder_pwd}             F3W@8$oh

${sso_PolicyHolderAccount}          EF0204
${sso_PolicyHolderAccount_pwd}      c31$@Wz#

${sso_PolicyHolderSearch}           EF0205
${sso_PolicyHolderSearch_pwd}       ew#R$5u@

${sso_PHClaims}                     EF0206
${sso_PHClaims_pwd}                 j0Yg6#p5

${sso_PHPayment}                    EF0207
${sso_PHPayment_pwd}                cCH@6#z1

${sso_PolicyHolderClaims}           EF0220
${sso_PolicyHolderClaims_pwd}       ELx24m0Sxxb5oQ3

${sso_PolicyHolderPayment}          EF0222
${sso_PolicyHolderPayment_pwd}      h5RQp8x7rxfxZIK

${sso_PolicyHolderEF}               EF0223
${sso_PolicyHolderEF_pwd}           V19hexYTxxJcj30

${sso_PolicyHolderBeeline}          EF0224
${sso_PolicyHolderBeeline_pwd}      y1x8Vx2mR6xdtEp

${sso_PHPaymentSupervisor}          EF0225
${sso_PHPaymentSupervisor_pwd}      UvKxx2uxxD9N4dS

# SSO AgentChannel PolicyHolder Logins
${sso_AgentSearch}                  EF0230
${sso_AgentSearch_pwd}              Axx4O2tx5kQhuG0

# SSO AccountChannel PolicyHolder Logins
${sso_PHAccount}                    EF0231
${sso_PHAccount_pwd}                x6QxVxGx7nT5rF0

#==========================================================================#
#                      SmartScreens Users	           		               #
#==========================================================================#
# SSO PolicyHolder SmartScreens CCS Logins
${sso_SSUser}                       EF0219
${sso_SSUser_pwd}                   u04$@rXe

${sso_SSOneUser}                    EF0235
${sso_SSOneUser_pwd}                N4iR2gxe0xbx8T3

${sso_SSTwoUser}                    EF0236
${sso_SSTwoUser_pwd}                Tfxx1xgxL08w3O4

${sso_SSThreeUser}                  EF0237
${sso_SSThreeUser_pwd}              PSxhx9xuIv573ef

${sso_SSFourUser}                   EF0238
${sso_SSFourUser_pwd}               ibxX9xgxIU4Z5ap

${sso_SSFiveUser}                   EF0239
${sso_SSFiveUser_pwd}               YxXxgo90BnxS1Z5

${sso_SSSixUser}                    EF0240
${sso_SSSixUser_pwd}                BtU9vxx1pg2Hx8N

# SSO AgentChannel PolicyHolder SmartScreen Logins
${sso_SSAgentUser}                  EF0241
${sso_SSAgentUser_pwd}              ZorxI1x27xbLFwG

# SSO AccountChannel PolicyHolder SmartScreen Logins
${sso_SSAccountUser}                EF0008
${sso_SSAccountUser_pwd}            RAxxce416wgx3Ob

${sso_SSAccountOneUser}             EF0009
${sso_SSAccountOneUser_pwd}         oxx10yVXf8x7ZxW

${sso_SSAccountTwoUser}             EF0011
${sso_SSAccountTwoUser_pwd}         ZxtgP5Txo3p4x89

#==========================================================================#
#                   Digital Messaging PolicyHolder Users	           	   #
#==========================================================================#
# Digital Messaging PolicyHolder Chat ccs logins
${DM_PH_ccs_uName}                  aflacr
${DM_PH_ccs_password}               jhe@322j87

#==========================================================================#
#                           Other Users				         	           #
#==========================================================================#
# SSO CCS Logins
${sso_ccsUser}                      EF0705
${sso_ccsUser_pwd}                  T6x4xv7VxBiP5ch

${sso_ccsManager}                   EF0706
${sso_ccsManager_pwd}               A4xxGv2x7EaK8qr

${sso_ccsAdmin}                     EF0707
${sso_ccsAdmin_pwd}                 o64xlxQ5Ix7XBcL
# ${gLoggedInUserName}              Geno

${sso_ccsDeveloper}                 EF0708
${sso_ccsDeveloper_pwd}             ErxSl6x85x7zgP4

# PolicyHolder CCS Logins
${PolicyHolder_ccs_uName}           PolicyHolderSpecialist_ccs
${gPWD}                             rules

# SSO Agent Logins
${sso_agent}                        darci_wertz
${sso_agent_pwd}                    Ani_P@v3R$6
