###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
# ${WebChat_URL}               https://customerservicechat.aflacws-syst.com/AflacAgentWebChat/index.html
${WebChat_URL}                 https://sell-syst.aflac.com
${AgentEmailWebForm_URL}       https://sell-syst.aflac.com
${Pega_SignIn_URL}             https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService
${sso_Pega_SignIn_URL}         https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService

#==========================================================================#
#                            C360 Agent Users                              #
#==========================================================================#
${sso_Agent}                   EF0213
${sso_Agent_pwd}               SaXq$5T7

${sso_Agent2}                  EF0214
${sso_Agent2_pwd}              G$@N6w#D

${sso_Agent3}                  EF0215
${sso_Agent3_pwd}              eM#154RE

${sso_Agent4}                  EF0216
${sso_Agent4_pwd}              fX2W7@8D

${sso_Agent5}                  EF0208
${sso_Agent5_pwd}              OY$96i4f

${sso_Agent6}                  EF0209
${sso_Agent6_pwd}              o#sQ0J$7

${sso_Agent7}                  EF0210
${sso_Agent7_pwd}              hCXb@$05

${sso_Agent8}                  EF0226
${sso_Agent8_pwd}              I4Ywc2xQxxlH5qG

${sso_Agent9}                  EF0227
${sso_Agent9_pwd}              S8z4xVMxxojGu9b

${sso_Agent10}                 EF0228
${sso_Agent10_pwd}             r19kKRxxx68AvBj

${sso_Manager}                 EF0211
${sso_Manager_pwd}             x97wYO#U

${sso_Claims}                  EF0212
${sso_Claims_pwd}              Hv@6$#Xi

${sso_General}                 EF0217
${sso_General_pwd}             BO8$n4P@

# AccountChannel Agent CCS Logins
${sso_AccountUser}             EF0001
${sso_AccountUser_pwd}         MTc57jx2nKxkIx8

${sso_AccountUserOne}          EF0006
${sso_AccountUserOne_pwd}      blV1QxAq0x7fIx4

${sso_AccountUserTwo}          EF0005
${sso_AccountUserTwo_pwd}      onZx60xQ52xxI7S

${sso_AccountUserThree}        EF0705
${sso_AccountUserThree_pwd}    T6x4xv7VxBiP5ch

${sso_AccountUserFour}         EF0706
${sso_AccountUserFour_pwd}     A4xxGv2x7EaK8qr

${sso_AccountUserFive}        EF0707
${sso_AccountUserFive_pwd}    o64xlxQ5Ix7XBcL

${sso_AccountUserSix}         EF0708
${sso_AccountUserSix_pwd}     ErxSl6x85x7zgP4

#==========================================================================#
#                       SmartScreens Agent Users                           #
#==========================================================================#
# Agent SmartScreen Logins - Please see PolicyHolder SysT.resource file

#==========================================================================#
#                       Digital Messaging Agent Users                      #
#==========================================================================#
#Digital Market Agent ccs logins
${DM_Agent_ccs_uName}          EF0705
${DM_Agent_ccs_password}       T6x4xv7VxBiP5ch

#==========================================================================#
#                           Other Users                                    #
#==========================================================================#
# SSO CCS Logins
${sso_ccsUser}                 EF0705
${sso_ccsUser_pwd}             T6x4xv7VxBiP5ch

${sso_ccsManager}              EF0706
${sso_ccsManager_pwd}          A4xxGv2x7EaK8qr

${sso_ccsAdmin}                EF0707
${sso_ccsAdmin_pwd}            o64xlxQ5Ix7XBcL
# ${gLoggedInUserName}         Geno

${sso_ccsDeveloper}            EF0708
${sso_ccsDeveloper_pwd}        ErxSl6x85x7zgP4

# SSO Agent Logins
#${sso_agent}                  darci_wertz
#${sso_agent_pwd}              Ani_P@v3R$9
# PAVE Agent Username
${gLoggedInUserName}         Darvin
