###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}              http://customerservicechat-dev.aflac.com/AflacMAXChatbot/index.html
${Pega_SignIn_URL}          https://customerservice-dev.aflac.com/prweb

# PolicyHolder CCS Logins
${MaxChat_ccs_uName}        MaxCS1
${gPWD}                     Aflac@001

