###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}        http://customerservicechat-intg.aflac.com/AflacMAXChatbot/index.html
${Pega_SignIn_URL}    https://customerservice-intg.aflac.com/prweb
${MaxWebChat_URL}     https://intg-max.aws.nonprod.aflac.com/


# PolicyHolder CCS Logins
${MaxChat_ccs_uName}    MaxCS1
${gPWD}    Aflac@001

#Digital Market Maxchat ccs logins
${DM_MaxChat_ccs_uName}    intggrptestuser19
${DM_MaxChat_ccs_password}    P@ssword1