###########################################################################
# All variables that are likely to be different between environments should
# be stored in the environment specific file
###########################################################################

* Variables
${WebChat_URL}            https://customerservicechat.aflacws-syst.com/AflacMAXChatbot/index.html
${Pega_SignIn_URL}        https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService
${sso_Pega_SignIn_URL}    https://customerservice-stg4.aflac.com/prweb/PRAuth/CustomerService
${MaxWebChat_URL}         https://myaflac.aflacqa.com/

# SSO Max CCS Logins
${sso_MaxChat}                   EF0202
${sso_MaxChat_pwd}               ftKC08#S

#Digital Market Maxchat ccs logins
${DM_MaxChat_ccs_uName}    A6876238
${DM_MaxChat_ccs_password}    P@ssword1

#####################################################################

# PolicyHolder CCS Logins
${MaxChat_ccs_uName}    MaxChatSpecialist_ccs
${gPWD}    Ani_P@v3R$2

# SSO Agent Logins
${sso_agent}        darci_wertz
${sso_agent_pwd}    Ani_P@v3R$6

${sso_MaxChat}        EF0705
${sso_MaxChat_pwd}    T6x4xv7VxBiP5ch

${sso_ccsManager}        EF0706
${sso_ccsManager_pwd}    A4xxGv2x7EaK8qr

${sso_ccsAdmin}         EF0707
${sso_ccsAdmin_pwd}     o64xlxQ5Ix7XBcL
# ${gLoggedInUserName}    Geno

${sso_ccsDeveloper}        EF0708
${sso_ccsDeveloper_pwd}    ErxSl6x85x7zgP4