FROM artifactory.aws.aflac.com/docker/python:3.13

HEALTHCHECK NONE

WORKDIR /pave

COPY pipelines/requirements.txt requirements.txt 

RUN python -m pip install --upgrade --ignore-installed pip && \
    pip install --upgrade -r requirements.txt