* Settings
# PAGE OBJECTS
Resource    ${EXECDIR}${/}ChatbotCommon${/}Chatbot_CommonKeywords.robot
# Page objects - Agent Chatbot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}Agent_CommonKeywords.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}AgentChatbot${/}Agent_ChatSurveyPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}AgentChatbot${/}Agent_CommonPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}AgentChatbot${/}Agent_ConnectToCcsPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}AgentChatbot${/}Agent_LandingPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}AgentCommon${/}AgentChatbot${/}Agent_VerifyMeModalPage.robot
# Page objects - CCS System
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}Ccs_Availability.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}Ccs_CommonKeywords.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_ChatInteractionPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_ConnectToCoBrowsePage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_Customer360TabsPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_LoginPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_ModalPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_MyWorkPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_NavSideBarPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_NavTopPage.robot
Resource    ${EXECDIR}${/}ChatbotCommon${/}CcsCommon${/}CcsSystem${/}Ccs_SearchPage.robot

